In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("DATA/matches.csv")

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             39 non-null     int64
 1   date                 39 non-null     str
 2   venue                39 non-null     str
 3   team1                39 non-null     str
 4   team2                39 non-null     str
 5   stage                39 non-null     str
 6   toss_winner          39 non-null     str
 7   toss_decision        39 non-null     str
 8   first_ings_score     38 non-null     float64
 9   first_ings_wkts      38 non-null     float64
 10  second_ings_score    38 non-null     float64
 11  second_ings_wkts     38 non-null     float64
 12  match_result         39 non-null     str
 13  match_winner         38 non-null     str
 14  wb_runs              15 non-null     float64
 15  wb_wickets           22 non-null     float64
 16  balls_left           38 non-null     float64
 17  player_of_the_match  38 non-null     str
 18  top_scorer           38 non-null     str
 19  highscore            38 non-null     float64
 20  best_bowling         38 non-null     str
 21  best_bowling_figure  38 non-null     str
 22  super_over_match     39 non-null     str
dtypes: float64(8), int64(1), str(14)
memory usage: 7.1 KB

In [22]:
data.isnull()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_result,match_winner,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
data.isnull().any()

match_id               False
date                   False
venue                  False
team1                  False
team2                  False
stage                  False
toss_winner            False
toss_decision          False
first_ings_score        True
first_ings_wkts         True
second_ings_score       True
second_ings_wkts        True
match_result           False
match_winner            True
balls_left              True
player_of_the_match     True
top_scorer              True
highscore               True
best_bowling            True
best_bowling_figure     True
super_over_match       False
dtype: bool

In [17]:
data.dropna(inplace = True)

In [19]:
data.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,balls_left,highscore
count,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000
mean,20.210526,190.526316,6.289474,175.500000,6.052632,10.684211,79.447368
std,11.477729,39.394565,2.470451,39.747684,2.670635,15.773918,24.521031
min,1.000000,75.000000,2.000000,77.000000,1.000000,0.000000,34.000000
25%,10.250000,159.750000,4.250000,159.250000,4.000000,0.250000,60.750000
50%,20.500000,197.000000,6.000000,180.000000,5.000000,6.000000,77.500000
75%,29.750000,215.000000,8.000000,203.750000,8.000000,12.000000,91.750000
max,39.000000,264.000000,10.000000,265.000000,10.000000,81.000000,152.000000

In [21]:
data['venue'].value_counts()

venue
M. Chinnaswamy Stadium, Bangalore                5
Wankhede Stadium, Mumbai                         4
Ekana Cricket Stadium, Lucknow                   4
Arun Jaitley Stadium, Delhi                      4
Narendra Modi Stadium, Ahmedabad                 4
Rajiv Gandhi International Stadium, Hyderabad    4
Barsapara Stadium, Guwahati                      3
New PCA Cricket Stadium, Mullanpur               3
Eden Gardens, Kolkata                            3
MA Chidambaram Stadium, Chennai                  3
Sawai Mansingh Stadium, Jaipur                   1
Name: count, dtype: int64

In [26]:
#select data
data.iloc[2:6,1:7]   #slicing

,date,venue,team1,team2,stage,toss_winner
2,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR
3,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS
4,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC
5,"April 02, 2026","Eden Gardens, Kolkata",KKR,SRH,League,KKR

In [34]:
rcb_tw = data['toss_winner']=='RCB'
cst = data['venue']=='M. Chinnaswamy Stadium, Bangalore'

In [36]:
data[rcb_tw & cst]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_result,match_winner,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,4.0,completed,RCB,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
22,23,"April 15, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,LSG,League,RCB,Bowl,146.0,10.0,...,5.0,completed,RCB,29.0,Josh Hazlewood,Virat Kohli,49.0,Rasikh Salam,4--24,No
33,34,"April 24, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,GT,League,RCB,Bowl,205.0,3.0,...,5.0,completed,RCB,7.0,Virat Kohli,Sai Sudarshan,100.0,Rashid Khan,2--49,No